CREATE TABLE GROUPS (
	GROUP_ID SERIAL PRIMARY KEY,
	GROUP_NAME TEXT
);

CREATE TABLE STUDENTS (
	STUDENT_ID SERIAL PRIMARY KEY,

	FIRST_NAME TEXT,
	LAST_NAME TEXT,
	EMAIL TEXT,
	PHONE_NUMBER TEXT,
	ENROLMENT_DATE DATE,
	CONSTRAINT FK_STUDENTS_GROUPS FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);